### ISSUE TITLE
fork your own appimage-builder

### ISSUE THREAD

**Issue by cabiste-dev** [Portal-2-Multiplayer-Mod/Portal-2-Multiplayer-Mod#125]
as the title says, you guys should fork your own appimage-builder instead of rlying on [the binary i made](https://github.com/Portal-2-Multiplayer-Mod/Portal-2-Multiplayer-Mod/blob/7e287c023c5afcf71dff67ddc28c7834c875cf76/tools/build-appimage.sh#L13) as i might delete the repo one day.

I recommend forking [my repo](https://github.com/cabiste-dev/appimage-builder) as it has slight patches that the main repo doesn't.

alternatively you can use [appimageKit](https://github.com/AppImage/appimagekit).

**Comment by OrsellGaming** [comment]
We aren't using AppImage anymore, we are switching to `nukita`, it provides a smaller executable size anyway. Plus it doesn't need multiple scripts or config files to do what we need it to do.

**Comment by OrsellGaming** [comment]
Well, for some reason, your docker compiler is not working and keeps using Python 3.12 instead of 3.10. It even says it is downloading 3.10, but in the end, it still is 3.12 for some reason. I've already tried to do what I could or knew to fix the issue. We switched to `nukita` because it was straightforward to use and wasn't convoluted like the appimage compiler. In the end, they both behave the same. Also, weren't you telling me in passing that most Linux users prefer to just run/compile from source instead of downloading the executable? I'm pretty done with messing with that stuff anyway because I have several other things I need to do that take priority, so if you really want us to use appimages you can help fix the issue.
