### ISSUE TITLE
No Internet Connection

### ISSUE THREAD

**Issue by amcmaster4** [Portal-2-Multiplayer-Mod/Portal-2-Multiplayer-Mod#129]
Whenever I try to install P2MM on my Steam Deck, it keeps saying "No Internet Connection Detected!"

**Comment by Amcmaster4** [comment]
Nevermind, had to go put in the mod files manually

**Comment by OrsellGaming** [comment]
Sorry for the late response @amcmaster4 . While it seems you figured it out, this isn't normal behavior. I may have already fixed this problem on the `dev` branch. However, I want to check something. Could you tell me if this happened either in Desktop or Gaming mode?

**Comment by amcmaster4** [comment]
This happened in desktop mode.

**Comment by OrsellGaming** [comment]
The launcher does not auto-run the game with Proton or download xclip for you. I should add to the install guides that Proton or something similar is needed, but the install guides mention that xclip needs to be manually installed. You will have to manually install xclip every time your Steam Deck updates due to the nature of the OS.

It's odd that the internet error is happening in Desktop mode, however, that shouldn't happen in the next update because I'm pretty sure that has been fixed.

**Comment by amcmaster4** [comment]
I did download XClip manually. Do I have to restart the deck after I run the command?

**Comment by OrsellGaming** [comment]
You do not.

**Comment by amcmaster4** [comment]
Ok, I will try and install XClip again

**Comment by amcmaster4** [comment]
Sorry about the long wait, but I got XClip to work :D
