### ISSUE TITLE
mp_coop_credits mapsupport issue (dedicated)

### ISSUE THREAD

**Issue by Nanoman2525** [Portal-2-Multiplayer-Mod/Portal-2-Multiplayer-Mod#46]
The map itself functions fine, but the credit names in the screen do not show at all since `coop_set_credits_index` and `coop_set_credits_jobtitle` do not work in the server console.

**Comment by OrsellGaming** [comment]
There is a .nut file Valve uses to store all the dev's names and such for the credits, the path for it is `C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\scripts\vscripts\credits\credits_coop.nut`. We should be able to change the CreditsList table to include the credits of the P2MM devs. We can also do other wacky stuff like make more turrets or other things appear on the conveyor, but other models or such not defined in the `credits_coop.nut` will not appear since it isn't present in the map. but we could probably add those too with a map support file.

**Comment by OrsellGaming** [comment]
Closing since dedicated is not planned anymore.
